# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/chat_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aservice/chat_service.proto\x12\x04\x63hat\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t2~\n\x0b\x43hatService\x12\x34\n\x0bSendMessage\x12\r.chat.Message\x1a\x16.google.protobuf.Empty\x12\x39\n\x0eReceiveMessage\x12\x16.google.protobuf.Empty\x1a\r.chat.Message0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service.chat_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=65
  _MESSAGE._serialized_end=104
  _CHATSERVICE._serialized_start=106
  _CHATSERVICE._serialized_end=232
# @@protoc_insertion_point(module_scope)
